import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { TextField,Button } from '@mui/material'
import { useState } from 'react'
export default function Home() {

  const [uname,setUname]= useState("");
  const router=useRouter();

  function handleClick(){
    router.push({
      pathname:"./search",
  })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <img
      src="/github.png"
      alt="Girl in a jacket"
      width="400"
      height="600"
      />
        <h1 className={styles.title}>
          Welcome to My Biller
        </h1>
        <p className={styles.description}>
          Create Bills and export to Excel
        </p>
        <div className={styles.grid}>
        <Button className="bg-orange-700 hover:bg-stone-700"
        variant="contained"
        sx={{
          color:"white",
          height:"48px",
          fontFamily:"Sofia"
        }}
        onClick={handleClick}
        >
        Open App
        </Button>
        </div>
      </main>
      <footer className={styles.footer}>
      <p className="text-3xl color-blue-200">
          madmax#1366
        </p>
      </footer>
    </div>
  )
}
