import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { TextField,Button } from '@mui/material'
import { useState } from 'react'
export default function Home() {

  const [uname,setUname]= useState("");
  const router=useRouter();

  function handleClick(){
    router.push({
      pathname:"./search",
  })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <img
      src="/github.png"
      alt="Girl in a jacket"
      width="400"
      height="600"
      />
        <h1 className={styles.title}>
          Welcome to Github Lookup
        </h1>
        <p className={styles.description}>
          Get started by searching a username
        </p>
        <div className={styles.grid}>
        <TextField 
        className='bg-blue-200'
        value={uname}
        placeholder="Search..."
        onChange={(e)=>setUname(e.currentTarget.value)}
        onKeyDown={(e)=>{if(e.key==="Enter")handleClick()}}
        />
        <Button  
        sx={{
          color:"white",
          height:"48px",
          alignItems:"flex-end",
          fontFamily:"Sofia"
        }}
        onClick={handleClick}
        >
        Search...
        </Button>
        </div>
      </main>
      <footer className={styles.footer}>
      <p className="color-blue-200">
          Get started by searching a username
        </p>
      </footer>
    </div>
  )
}
