import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { TextField,Button } from '@mui/material'
import { useState } from 'react'
export default function Home() {

  const [uname,setUname]= useState("");
  const router=useRouter();

  function handleClick(){
    router.push({
      pathname:"./search",
      query:{
          "search":uname,
      }
  })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Github Lookup
        </h1>

        <p className={styles.description}>
          Get started by searching a username
          
        </p>

        <div className={styles.grid}>
        <TextField value={uname} onChange={(e)=>setUname(e.currentTarget.value)} onKeyDown={(e)=>{if(e.key==="Enter")handleClick()}}></TextField>
        <Button onClick={handleClick}>search</Button>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
